# Statically linked PJRT CPU plugin.
#
# Note: cc_static_library only available in bazel >= 7.4.0:
cc_static_library(
    name = "pjrt_c_api_cpu",
    deps = [
        "@xla//xla/pjrt/c:pjrt_c_api_cpu",
    ],
)
