package xlabuilder

/***** File generated by ./cmd/xlabuilder_codegen, based on node_types.txt. Don't edit it directly. *****/

// NodeType enumerates the various types of Nodes supported by XLA.
// A node represent a basic computation operation (XlaOp).
type NodeType int32

const (
	InvalidNode NodeType = iota
	ConstantNode
	IotaNode
	ParameterNode
	ConvertTypeNode
	WhereNode
	TupleNode
	GetTupleElementNode
	ReshapeNode
	BroadcastNode
	BroadcastInDimNode
	ReduceSumNode
	ReduceMaxNode
	ReduceMultiplyNode
	SliceNode
	PadNode
	GatherNode
	ScatterNode
	ConcatenateNode
	ConvGeneralDilatedNode
	ReverseNode
	TransposeNode
	ReduceWindowNode
	SelectAndScatterNode
	BatchNormTrainingNode
	BatchNormInferenceNode
	BatchNormGradNode
	DotGeneralNode
	ArgMinMaxNode
	FftNode
	AbsNode
	NegNode
	ExpNode
	Expm1Node
	FloorNode
	CeilNode
	RoundNode
	LogNode
	Log1pNode
	LogicalNotNode
	LogisticNode
	SignNode
	ClzNode
	CosNode
	SinNode
	TanhNode
	SqrtNode
	RsqrtNode
	ImagNode
	RealNode
	ConjNode
	AddNode
	MulNode
	SubNode
	DivNode
	RemNode
	AndNode
	OrNode
	XorNode
	DotNode
	MinNode
	MaxNode
	PowNode
	ComplexNode
	EqualNode
	NotEqualNode
	GreaterOrEqualNode
	GreaterThanNode
	LessOrEqualNode
	LessThanNode
	EqualTotalOrderNode
	NotEqualTotalOrderNode
	GreaterOrEqualTotalOrderNode
	GreaterThanTotalOrderNode
	LessOrEqualTotalOrderNode
	LessThanTotalOrderNode
	RngBitGeneratorNode
	RngNormalNode
	RngUniformNode
)
