// Code generated by "stringer -type ReduceOpType reduce.go"; DO NOT EDIT.

package xlabuilder

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UndefinedReduceType-0]
	_ = x[ReduceSumType-1]
	_ = x[ReduceProductType-2]
	_ = x[ReduceMaxType-3]
	_ = x[ReduceMinType-4]
	_ = x[ReduceAndType-5]
	_ = x[ReduceOrType-6]
}

const _ReduceOpType_name = "UndefinedReduceTypeReduceSumTypeReduceProductTypeReduceMaxTypeReduceMinTypeReduceAndTypeReduceOrType"

var _ReduceOpType_index = [...]uint8{0, 19, 32, 49, 62, 75, 88, 100}

func (i ReduceOpType) String() string {
	if i < 0 || i >= ReduceOpType(len(_ReduceOpType_index)-1) {
		return "ReduceOpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReduceOpType_name[_ReduceOpType_index[i]:_ReduceOpType_index[i+1]]
}
